/**
 * shared/maps.js — Single source of truth for map name normalization.
 *
 * Exports:
 *   MAP_ALIASES       — Comprehensive alias map (French, English, camelCase, PascalCase → canonical English name)
 *   normalizeMap(name) — Returns MAP_ALIASES[name] || name
 *   MAP_NORMALIZATION  — French → English subset (for frontend display / i18n)
 */

// ── Comprehensive alias map ──────────────────────────────────────────────────
// Merged from: app.js (MAP_NORMALIZATION), server.js (MAP_ALIASES),
//              sync.js (MAP_ALIASES), sync-compact.js (MAP_ALIASES)
export const MAP_ALIASES = {
  // French → English (from app.js MAP_NORMALIZATION + sync.js)
  "Afrique":             "Africa",
  "Alpes":               "Alps",
  "Arctique":            "Arctic",
  "Asie":                "Asia",
  "Australie":           "Australia",
  "Amérique du Nord":    "North America",
  "Amérique du Sud":     "South America",
  "Europe":              "Europe",
  "Islande":             "Iceland",
  "Japon":               "Japan",
  "Italie":              "Italy",
  "Italia":              "Italy",
  "Delta du Nil":        "Nile Delta",
  "Fleuve Amazone":      "Amazon River",
  "Mer Noire":           "Black Sea",
  "Détroit du Bosphore": "Bosphorus Straits",
  "Bosphore":            "Bosphorus Straits",
  "Détroit de Béring":   "Bering Strait",
  "Mer de Béring":       "Bering Sea",
  "Détroit de Gibraltar":"Strait of Gibraltar",
  "Détroit d'Hormuz":    "Strait of Hormuz",
  "Entre Deux Mers":     "Between Two Seas",
  "Monde":               "World",
  "Pangée":              "Pangaea",
  "Iénisseï":            "Yenisei",
  "Hawaï":               "Hawaii",
  "Strait Of Malacca":   "Strait of Malacca",
  "Antarctique":         "Antarctica",
  "Mer Égée":            "Aegean",
  "Mer de l'Archipel":   "Archipelago Sea",
  "Basse-Californie":    "Baja California",
  "Caucase":             "Caucasus",
  "Îles Malouines":      "Falkland Islands",
  "Îles Féroé":          "Faroe Islands",
  "Quatre Îles":         "Four Islands",
  "Porte de l'Atlantique": "Gateway to the Atlantic",
  "Grands Lacs":         "Great Lakes",
  "Golfe du Saint-Laurent": "Gulf of St. Lawrence",
  "Chalcidique":         "Halkidiki",
  "Lisbonne":            "Lisbon",
  "Lune":                "Luna",
  "Voie lactée":         "Milkyway",
  "Montréal":            "Montreal",
  "New York":            "New York City",
  "Le Passage":          "Passage",
  "Pluton":              "Pluto",
  "Encerclé":            "Surrounded",
  "La Boîte":            "The Box",
  "Rêve des Marchands":  "Traders Dream",
  "Deux Lacs":           "Two Lakes",
  "Monde inversé":       "World Rotated",

  // English identity mappings (from server.js + sync.js)
  "World":                   "World",
  "Asia":                    "Asia",
  "Africa":                  "Africa",
  "Australia":               "Australia",
  "Iceland":                 "Iceland",
  "North America":           "North America",
  "South America":           "South America",
  "Japan":                   "Japan",
  "Italy":                   "Italy",
  "Britannia":               "Britannia",
  "Mars":                    "Mars",
  "Pluto":                   "Pluto",
  "Pangaea":                 "Pangaea",
  "Alps":                    "Alps",
  "Hawaii":                  "Hawaii",
  "Arctic":                  "Arctic",
  "Nile Delta":              "Nile Delta",
  "Amazon River":            "Amazon River",
  "Black Sea":               "Black Sea",
  "Bosphorus Straits":       "Bosphorus Straits",
  "Bering Strait":           "Bering Strait",
  "Bering Sea":              "Bering Sea",
  "Strait of Gibraltar":     "Strait of Gibraltar",
  "Strait of Hormuz":        "Strait of Hormuz",
  "Between Two Seas":        "Between Two Seas",
  "San Francisco":           "San Francisco",
  "New York City":           "New York City",
  "Montreal":                "Montreal",
  "Passage":                 "Passage",
  "The Box":                 "The Box",
  "Traders Dream":           "Traders Dream",
  "Yenisei":                 "Yenisei",
  "Baikal":                  "Baikal",
  "Gulf of St. Lawrence":    "Gulf of St. Lawrence",
  "Gateway to the Atlantic": "Gateway to the Atlantic",
  "Falkland Islands":        "Falkland Islands",
  "Faroe Islands":           "Faroe Islands",
  "Four Islands":            "Four Islands",
  "Lemnos":                  "Lemnos",
  "Aegean":                  "Aegean",
  "Halkidiki":               "Halkidiki",
  "Lisbon":                  "Lisbon",
  "Mena":                    "Mena",
  "Achiran":                 "Achiran",
  "Svalmel":                 "Svalmel",
  "Manicouagan":             "Manicouagan",
  "Sierpinski":              "Sierpinski",
  "Surrounded":              "Surrounded",
  "Two Lakes":               "Two Lakes",
  "Deglaciated Antarctica":  "Deglaciated Antarctica",
  "World Rotated":           "World Rotated",
  "East Asia":               "East Asia",
  "Europe Classic":          "Europe Classic",
  "Britannia Classic":       "Britannia Classic",

  // camelCase / PascalCase → canonical (from sync.js)
  "ArchipelagoSea":          "Archipelago Sea",
  "Archipelago Sea":         "Archipelago Sea",
  "Antarctica":              "Antarctica",
  "BeringStrait":            "Bering Strait",
  "BetweenTwoSeas":          "Between Two Seas",
  "BlackSea":                "Black Sea",
  "Caucasus":                "Caucasus",
  "Conakry":                 "Conakry",
  "Danish Straits":          "Danish Straits",
  "Didier":                  "Didier",
  "Didier (France)":         "Didier (France)",
  "Dyslexdria":              "Dyslexdria",
  "GatewayToTheAtlantic":    "Gateway to the Atlantic",
  "Giant_World_Map":         "Giant World Map",
  "Great Lakes":             "Great Lakes",
  "Los Angeles":             "Los Angeles",
  "Luna":                    "Luna",
  "Mare Nostrum":            "Mare Nostrum",
  "MENA":                    "MENA",
  "Middle East":             "Middle East",
  "Milkyway":                "Milkyway",
  "NorthAmerica":            "North America",
  "Northwest Passage":       "Northwest Passage",
  "Oceania":                 "Oceania",
  "SanFrancisco":            "San Francisco",
  "Americas":                "Americas",
  "Taiwan Strait":           "Taiwan Strait",
  "TheBox":                  "The Box",
  "Tourney1":                "Tourney 1",
  "Tourney2":                "Tourney 2",
  "Tourney3":                "Tourney 3",
  "Tourney4":                "Tourney 4",
  "Venice":                  "Venice",
  "Baja California":         "Baja California",
  "Baikal (Nuke Wars)":      "Baikal (Nuke Wars)",
};

/**
 * Normalize a map name to its canonical English form.
 * Returns the alias if found, otherwise returns the name unchanged.
 */
export function normalizeMap(name) {
  return MAP_ALIASES[name] || name;
}

// ── French → English subset (for frontend display / i18n) ────────────────────
// Used by app.js to convert French API responses to English map names
export const MAP_NORMALIZATION = {
  "Afrique": "Africa",
  "Alpes": "Alps",
  "Arctique": "Arctic",
  "Asie": "Asia",
  "Australie": "Australia",
  "Amérique du Nord": "North America",
  "Amérique du Sud": "South America",
  "Europe": "Europe",
  "Islande": "Iceland",
  "Japon": "Japan",
  "Italie": "Italy",
  "Italia": "Italy",
  "Delta du Nil": "Nile Delta",
  "Fleuve Amazone": "Amazon River",
  "Mer Noire": "Black Sea",
  "Détroit du Bosphore": "Bosphorus Straits",
  "Bosphore": "Bosphorus Straits",
  "Détroit de Béring": "Bering Strait",
  "Mer de Béring": "Bering Sea",
  "Détroit de Gibraltar": "Strait of Gibraltar",
  "Détroit d'Hormuz": "Strait of Hormuz",
  "Entre Deux Mers": "Between Two Seas",
  "Monde": "World",
  "Pangée": "Pangaea",
  "Iénisseï": "Yenisei",
  "Hawaï": "Hawaii",
  "Strait Of Malacca": "Strait of Malacca",
  "Antarctique": "Antarctica",
  "Mer Égée": "Aegean",
  "Mer de l'Archipel": "Archipelago Sea",
  "Basse-Californie": "Baja California",
  "Caucase": "Caucasus",
  "Îles Malouines": "Falkland Islands",
  "Îles Féroé": "Faroe Islands",
  "Quatre Îles": "Four Islands",
  "Porte de l'Atlantique": "Gateway to the Atlantic",
  "Grands Lacs": "Great Lakes",
  "Golfe du Saint-Laurent": "Gulf of St. Lawrence",
  "Chalcidique": "Halkidiki",
  "Lisbonne": "Lisbon",
  "Lune": "Luna",
  "Voie lactée": "Milkyway",
  "Montréal": "Montreal",
  "New York": "New York City",
  "Le Passage": "Passage",
  "Pluton": "Pluto",
  "Encerclé": "Surrounded",
  "La Boîte": "The Box",
  "Rêve des Marchands": "Traders Dream",
  "Deux Lacs": "Two Lakes",
  "Monde inversé": "World Rotated"
};
